#dedicated to the Boomers

import time



print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()





time.sleep(5)
print("                                                                             this one goes out to all tha boomers out there")    
time.sleep(5)
print()
time.sleep(5)
print()
time.sleep(5)
print()
time.sleep(5)
print("                                                                                                      /‘     , - ‘")                             
time.sleep(5)
print("                                                                                          _.....-------.../;_  ,..--")
time.sleep(5)
print("                                                                                        ..                      . ,   ")
time.sleep(5)
print("                                                                                   , +`                          +., ")
time.sleep(5)
print("                                                                                 -                                    *..")
time.sleep(5)
print("                                                                               +                ,....,,,                 -,")
time.sleep(5)
print("                                                                            ,*                                              .") 
time.sleep(5)
print("                                                                          ,                                                 `*,")
time.sleep(5)
print("                                                                          *                                                   * ,")
time.sleep(5)
print("                                                                        *                            _                          ,")
time.sleep(5)
print("                                                                      /`                               ,                          \"") 
time.sleep(5)
print("                                                                     /                         ..- `   \                          '\"")
time.sleep(5)
print("                                                                    /                        /          :                         ,”")
time.sleep(5)
print("                                                                    :                        /            \                        \ :")
time.sleep(5)
print("                                                                    /                       /             :                         :*.")
time.sleep(5)
print("                                                                    :                      /              |                           |")
time.sleep(5)
print("                                                                    |                     ,               ,                     _     |")
time.sleep(5)
print("                                                                    \                     :              :                 …--.    .  ,")
time.sleep(5)
print("                                                                   \                     |              ,               , *     ,    ,")
time.sleep(5)
print("                                                                     ,                    |             ,             *          ,    /")
time.sleep(5)
print("                                                                     \                    :            ,            ,            ,   .")
time.sleep(5)
print("                                                                      \             \  \  ,            ,          .             ,   /")
time.sleep(5)
print("                                              ,.-,                     \            :-.::,,           *          /            /    /")
time.sleep(5)
print("                                                                        \ .         *----.,,,___                /             /   ,")
time.sleep(5)
print("                                              :    \                     ,*               `-........           /           +   /")
time.sleep(5)
print("                                              |    \                      ,                     ***  .,      /           *  ..")
time.sleep(5)
print("                                               ,    , .. ---,,           ,                          ,, - .            .  , ,.")
time.sleep(5)
print("                                                . .           * ,         :                     _…,,_*.,.         ,,      /")
time.sleep(5)
print("                                                 /              * ,,      ,                        …,,,,* -...__,,      /")
time.sleep(5)
print("                                               /  _                \ ,, ,,,,,,,,,,                 *         ***....  /")
time.sleep(5)
print("                                           _..:,.   ,                             . .\                            ``.-")
time.sleep(5)
print("                                         .     ________                       \ ,     ,                      |     |")
time.sleep(5)
print("                                         /        *********~..                         ..                          ,")
time.sleep(5)
print("                                         |                           .                   \.  ..\ …………….,,,,,,,,,.,,")
time.sleep(5)
print("                                         |                           :                       -    * , \ \ \"")
time.sleep(5)
print("                                         ,                          *           …,              / * -----")
time.sleep(5)
print("                                         ..                        ,,_     ……+....,_,,,:........")
time.sleep(5)
print("                                           ..                _.... | +++++")
time.sleep(5)
print("                                               -,,            **   ,,  ,")
time.sleep(5)
print("                                           |     ~ ,         _..    *:")
time.sleep(5)
print("                                            ,   `  ` ------- *       :")
time.sleep(5)
print("                                            `,        ```````        ,")
time.sleep(5)
print("                                             * ,,                   ,,")
time.sleep(5)
print("                                               * -..,_      ……")
time.sleep(5)
print("                                                       ………-")
time.sleep(5)

print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
            
            
print()
print("                                               . ~ ~  ` ` `”” . . , ...,,")
time.sleep(5)
print("                                               .. ‘                       ‘")  
time.sleep(5)
print("                                                                            ‘ ‘..")
time.sleep(5)
print("                                           “ “                                  .")
time.sleep(5)
print("                                         ‘                                        ;")
time.sleep(5)
print("                                       ‘                                          ,")
time.sleep(5)
print("                                      “                     *. . . . _ _ _ _,-")
time.sleep(5)
print("                                     `                          . ,   ,")
time.sleep(5)
print("                                    :                              - - . .") 
time.sleep(5)
print("                                   .                                      - - .") 
time.sleep(5)
print("                                   .                                            * ,")
time.sleep(5)
print("                                  ,                                                 ,") 
time.sleep(5)
print("                        . ‘ ‘- , ,.                          . - “,` `` ` ‘ ‘ ‘")
time.sleep(5)
print("                        ,         ,                        .’     ‘  ` ` ‘  \ `’ . ,*. ` ` :")
time.sleep(5)
print("                         .        .                     .-       |      `    \. `    .     ,")
time.sleep(5)
print("                          .       ;                   -           .       . - `       ,    ,")
time.sleep(5)
print("                            - /   ,      , , ,_     .              . - `            .    .")
time.sleep(5)
print("                             /     , , ‘         . .                                ,    .")
time.sleep(5)
print("                            .      .                                              .   . . . ") 
time.sleep(5)
print("                           ,      .    . . - - - .                             -    |     .")
time.sleep(5)
print("                          ,       ,         /             , -                              ,")
time.sleep(5)
print("                         ,         ,       {                \                       `    ,")
time.sleep(5)
print("                         ,          ,       . .              . ,          . `   . ‘     ,. . . . .           .  . . . .") 
time.sleep(5)
print("                         ,         , . _                        . . . .     .       . .           .      . ‘  ‘        .. ")
time.sleep(5)
print("                        .         .      . . . . . . .,                 .  `    . - .                .  ,                 , ")
time.sleep(5)
print("                       ,          ,                   ‘. . . . . . . ~  . . .    .                  ..                   .")
time.sleep(5)
print("                        .           .                                        , , ,/                   ./                    ,")
time.sleep(5)
print("                        ,             - _                              . .      ,                     :                    ,")
time.sleep(5)
print("                        ,                   . . . . . . .             ,          ,                     ,                     ,") 
time.sleep(5)
print("                        ,                               ,            ,           ,                    . .                   .")
time.sleep(5)
print("                       / ‘                               ‘\,        ,      . * *,                    ,   ,                  ,")
time.sleep(5)
print("                     ;                                    ,        .      /     .                    .   ,                  .")
time.sleep(5)
print("                     .                                     .      .      .       .                  / .   ,                 ,")
time.sleep(5)
print("                     .          - ., ,                 . _ ,     ,              ,                 ,   ‘ .                 .")
time.sleep(5)
print("                      . . . . .  ‘     . , , , , , , , , ,    .   ;                ,               ,     ,                ,")
time.sleep(5)
print("                                                                . .             /  .                ,   ,                ,")
time.sleep(5)
print("                                                                  . ,              ,                ,   ,               ,")
time.sleep(5)
print("                                                                     .  ,            ,              ,   ,             ,")
time.sleep(5)
print("                                                                         . . _ . . ‘ ,            ,     ,          ,")
time.sleep(5)
print("                                                                                       , ,       ,        ,  ,  , ,")
time.sleep(5)
print("                                                                                           ~ . . ")

print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
                
               





print("                       ,                                                       …………..,")                            
time.sleep(5)
print("                      .*,  .                                            .,, ---    `````````  ---..")
time.sleep(5)
print("                      -...,/…..----------.....,,,              ....~                             ....")
time.sleep(5)
print("                       `*./--     ..                  …     …                                     *  . ")
time.sleep(5)
print("                     . ~... ~~**                   ```  …                                           **..")
time.sleep(5)
print("                . . /***...--**** _    .               ```*..                                            *...")
time.sleep(5)
print("                  . --***``     “””””””  *..                `*..                                           ` ,.")
time.sleep(5)
print("               . -**`  _        ** ````   ` …                 *\.                                             . ")
time.sleep(5)
print("                .     ..--            ,       : .,               ,,                                           ` .,")
time.sleep(5)
print("               .    ….-           .---..       //\.                .                                             *.")
time.sleep(5)
print("               }    .-*`           *`  ```       \....               \                                              \"") 
time.sleep(5)
print("              ,*    *`    .        *           -,,,,,,\               \          …..,                             \"")
time.sleep(5)
print("              /`    `    ***’        .      *  - …. |.             | ……----------,,,,,,,,,,,,                       *")
time.sleep(5)
print("             *    .      .            *---        ,... *.             , ***                **....                   |")
time.sleep(5)
print("            /     *      .       .      ``         *=..  ..         //                         ``` ..,               | ")
time.sleep(5)
print("           *      *,     *   ,.*         _           * .   . . ....*                                *...             |")
time.sleep(5)
print("           /       *   ,, ....*`     .._   .            .   ***.**                                      .            *  ")   
time.sleep(5)
print("           *        *..,         .          .            .      /                                                      *")
time.sleep(5)
print("           /         *. .        .          .            .      .                                                       | ")
time.sleep(5)
print("           .           \.          .       .             /      |                                                     . |")
time.sleep(5)
print("           ,           *          ` **-  .           ,`       |                                                     . /")
time.sleep(5)
print("           .             .                 \.      . * `       *                                                    / /")
time.sleep(5)
print("           *            *,                *. …- .  .        `                                                  /  .")
time.sleep(5)
print("           *.            *..              ,- *  ..----        *                                               ..   .")
time.sleep(5)
print("             \            *. ...____ ::....-** `  `*       *                                            ..    /")
time.sleep(5)
print("             * - _      .*  **-----******        .  *      *                                         , *   ,*")
time.sleep(5)
print("                * …..**       …....              *  *       *.                                  . .       /*")
time.sleep(5)
print("                 *  *         .  *...: *..      *     *  :        *.                              . -       ..")
time.sleep(5)
print("                   \          .** ` ` .  *,       *    * *       / *..                     . . * * `    , *    ")
time.sleep(5)
print("                   * ,      |   .-,,  `   *,      |    |*- - ---|__+.            ,,,,--***       . *")
time.sleep(5)
print("                        ,,,__,*```\        ,,,,,,*,,-*************\      , ,,,.***          , ,*")
time.sleep(5)
print("                         ****.`     *      *     ,-*,,                   *,,,-                   l")
time.sleep(5)
print("                               |,                  , -** ,,              ,,--                   .*  *")
time.sleep(5)
print("                                ..,                |,*  ,                ,                    .")
time.sleep(5)
print("                                   . ,             :*   *              *                  * `    ")              
time.sleep(5)
print("                                      --,,_       -   |              /*                * `")
time.sleep(5)
print("                                        ``~~-__\\_|      . .---/          ,,,, `*,,,,,*")
time.sleep(5)
print("                                                ``--------,. /    .          . ")
time.sleep(5)
print("                                                          . .   -..+      +-*    ")       
time.sleep(5)
print("                                                          . .  _`/     ,")
time.sleep(5)
print("                                                           ..: _|    - *")
time.sleep(5)
print("                                                                  |   *")
time.sleep(5)
print("                                                                  |  *")
time.sleep(5)
print("                                                           |/")

print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
 
                       
print()
time.sleep(5)
print("                                                                          ,--, ") 
time.sleep(5)
print("                                                                         (   ),,")
time.sleep(5)
print("                                                                         -      -,")
time.sleep(5)
print("                                                                       *         +")
time.sleep(5)
print("                                                                      /           *")
time.sleep(5)
print("                                                                     *            ;  ")  
time.sleep(5)
print("                                                                     ;             ,,.,")                  
time.sleep(5)
print("                                                                     ,               ,                       ....") 
time.sleep(5)
print("                                                                      ,              ,          ,.....,     , ,  \"")
time.sleep(5)
print("                                                                      |              ,       .-       -     // --|    _") 
time.sleep(5)
print("                                                                    ,,   .            , .. .-          *\  |:  --,  -   ,")
time.sleep(5)
print("                                                                   \ /,,  *-          - |-              \  |,  , |  /   \ ")
time.sleep(5)
print("                                                                    \/ -                |      ___     \_  ,-.../ ,  -,  ..,")
time.sleep(5)
print("                                                                    \                  |            +      ` ,  _       -~  ,")
time.sleep(5)
print("                                                                    _.,     ,. ____ ____, , , )____`   , , ___-  ,")
time.sleep(5)
print("                                                                   /    ----/\                  / ) )           / ( / , - .  \\ ,")
time.sleep(5)
print("                                                                   |         , ,                 `-``                         \, \ ")
time.sleep(5)
print("                                                                  ,         ,   ,                                               , ,..")
time.sleep(5)
print("                                                                  ,         ,   ,                                                ,.,,`/")
time.sleep(5)
print("                                                                ,          ,   ,                                                \"")
time.sleep(5)
print("                                                                 ,          ,    ,                                                ;")
time.sleep(5)
print("                                                                 . ……..,,,,,     ……………………………………………………………………………………………………………………………………")
time.sleep(5)
print("                                                                ,           ,    ,                                                  ,")
time.sleep(5)
print("                                                                .           ,    ,                                                   , ")
time.sleep(5)
print("                                                               ,             , ,,                                                     ,")
time.sleep(5)
print("                                                              ,             `                                                          ,")
time.sleep(5)
print("                                                              ,                                                                         , ")
time.sleep(5)
print("                                                              ,                                                                         -,")
time.sleep(5)
print("                                                              …………………………………………………..:…………………………………………………………………………………………………………………………………………………")
time.sleep(5)


print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
                            

                     


